### ISSUE TITLE
Dropping two items of the same type does not work

### ISSUE THREAD

**Issue by Nubebuster** [luna-rs/luna#198]
Dropping two items at the same position throws this error

`[07 Jan 2020 16:48:19] [io.luna.game.event.EventListenerPipeline] [GameService RUNNING]
ERROR: Catching
io.luna.game.plugin.ScriptExecutionException: java.lang.IllegalStateException: Entity could not be added to chunk.
	at io.luna.game.event.EventListener.apply(EventListener.java:64) ~[classes/:?]
	at io.luna.game.event.EventListenerPipeline.post(EventListenerPipeline.java:70) ~[classes/:?]
	at io.luna.game.plugin.PluginManager.post(PluginManager.java:45) ~[classes/:?]
	at io.luna.net.msg.GameMessageReader.postEvent(GameMessageReader.java:66) ~[classes/:?]
	at io.luna.net.client.GameClient.handleDecodedMessages(GameClient.java:69) ~[classes/:?]
	at io.luna.game.model.World.preSynchronize(World.java:241) ~[classes/:?]
	at io.luna.game.model.World.loop(World.java:223) ~[classes/:?]
	at io.luna.game.service.GameService.runOneIteration(GameService.java:131) ~[classes/:?]
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:195) ~[guava-27.0.1-jre.jar:?]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119) ~[guava-27.0.1-jre.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Entity could not be added to chunk.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507) ~[guava-27.0.1-jre.jar:?]
	at io.luna.game.model.chunk.ChunkRepository.add(ChunkRepository.java:47) ~[classes/:?]
	at io.luna.game.model.chunk.Chunk.add(Chunk.java:58) ~[classes/:?]
	at io.luna.game.model.Entity.setCurrentChunk(Entity.java:217) ~[classes/:?]
	at io.luna.game.model.Entity.setState(Entity.java:170) ~[classes/:?]
	at io.luna.game.model.item.GroundItemList.addToSet(GroundItemList.java:195) ~[classes/:?]
	at io.luna.game.model.item.GroundItemList.add(GroundItemList.java:138) ~[classes/:?]
	at io.luna.game.model.item.GroundItemList.onRegister(GroundItemList.java:57) ~[classes/:?]
	at io.luna.game.model.item.GroundItemList.onRegister(GroundItemList.java:23) ~[classes/:?]
	at io.luna.game.model.EntityList.register(EntityList.java:113) ~[classes/:?]
	at world.player.item.dropItem.DropItem.dropItem(Unknown Source) ~[classes/:?]
	at world.player.item.dropItem.DropItem$2.invoke(dropItem.kts:51) ~[classes/:?]
	at world.player.item.dropItem.DropItem$2.invoke(dropItem.kts:10) ~[classes/:?]
	at api.event.InterceptFilter$then$wrappedAction$1.invoke(InterceptFilter.kt:24) ~[classes/:?]
	at api.event.InterceptFilter$then$wrappedAction$1.invoke(InterceptFilter.kt:14) ~[classes/:?]
	at api.event.InterceptFilter$sam$java_util_function_Consumer$0.accept(InterceptFilter.kt) ~[classes/:?]
	at io.luna.game.event.EventListener.apply(EventListener.java:62) ~[classes/:?]
	... 15 more
[07 Jan 2020 16:49:01] [io.luna.game.task.Task] [GameService RUNNING]
ERROR: Catching
java.lang.NullPointerException: null
	at io.luna.game.model.item.GroundItem.toString(GroundItem.java:94) ~[classes/:?]
	at java.lang.String.valueOf(String.java:2951) ~[?:?]
	at io.luna.game.model.Entity.setState(Entity.java:168) ~[classes/:?]
	at io.luna.game.model.item.GroundItemList.addToSet(GroundItemList.java:195) ~[classes/:?]
	at io.luna.game.model.item.GroundItemList.add(GroundItemList.java:138) ~[classes/:?]
	at io.luna.game.model.item.GroundItemList.onRegister(GroundItemList.java:57) ~[classes/:?]
	at io.luna.game.model.item.GroundItemList.onRegister(GroundItemList.java:23) ~[classes/:?]
	at io.luna.game.model.EntityList.register(EntityList.java:113) ~[classes/:?]
	at world.player.item.groundItem.GroundItemTask.processRegistrations(GroundItemTask.kt:98) ~[classes/:?]
	at world.player.item.groundItem.GroundItemTask.execute(GroundItemTask.kt:46) ~[classes/:?]
	at io.luna.game.task.Task.runTask(Task.java:92) ~[classes/:?]
	at io.luna.game.task.TaskManager.runTaskIteration(TaskManager.java:73) ~[classes/:?]
	at io.luna.game.model.World.loop(World.java:220) ~[classes/:?]
	at io.luna.game.service.GameService.runOneIteration(GameService.java:131) ~[classes/:?]
	at com.google.common.util.concurrent.AbstractScheduledService$ServiceDelegate$Task.run(AbstractScheduledService.java:195) ~[guava-27.0.1-jre.jar:?]
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119) ~[guava-27.0.1-jre.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

Let me know if opening issues like this is appreciated. I assume many of these types of issues have to do with some major part of the project being in the works.

Cheers

**Comment by lare96** [comment]
Yes, opening issues for bugs is always greatly appreciated. I'll close the issue when its fixed on master
